# Generated by Django 4.2.6 on 2023-10-05 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sadman',
            name='images',
            field=models.FileField(blank=True, null=True, upload_to='images/'),
        ),
    ]
