# Generated by Django 4.2.6 on 2023-10-12 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_sadman_images'),
    ]

    operations = [
        migrations.CreateModel(
            name='product2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('subcategory', models.CharField(max_length=100)),
                ('price', models.IntegerField(default=0)),
                ('dese', models.CharField(max_length=300)),
                ('pub_data', models.DateField()),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
