# Generated by Django 4.2.6 on 2023-10-30 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_orders'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='items_json',
        ),
    ]
