# Generated by Django 4.2.6 on 2023-10-30 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_remove_orders_items_json'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='phone_no',
            field=models.CharField(max_length=1500),
        ),
    ]
